### ISSUE TITLE
Removing commit history attached to my name

### ISSUE THREAD

**Issue by ncthis** [anyTV/HeartbeatTM#124]
Hey everyone,

Since I stopped working, the commit history attached to my name is here in the repo. If possible, I'd like some help in removing it, as it covers some of my other open source contributions.

So, if you guys don't have any plans on making this a private repo under anyTV, can you run this script for me after reviewing?

The script: https://gist.githubusercontent.com/ncthis/24421846c11b76a660b9/raw/032e027278031dea702a1c845a8e127ed12d963d/remove-ncthis.sh

This will only change the author (name and email) of the commits attributed to me. Won't change your source of history of other commits.

After this is done, you will need to
```sh
git fetch --all
git reset --hard origin/master
```
to update your local repo.

Would really appreciate if one of you could take a look at this.

**Comment by ncthis** [comment]
@cedricabuso @ravenjohn Anyone here who can help me with this please?

**Comment by ravenjohn** [comment]
done :)

**Comment by ncthis** [comment]
@ravenjohn Thanks! But there's a small issue. You updated the `gh-pages` branch. Can you `git checkout master` and run the script please?

Really appreciate you taking time out to look into this.

**Comment by ravenjohn** [comment]
I am on master branch. I just edited my git config to push on both master and gh-pages. That's why there's an arrow from `master -> gh-pages`.

**Comment by ravenjohn** [comment]
I'll just clone and try again

**Comment by ravenjohn** [comment]
that's it. it worked :)

**Comment by ncthis** [comment]
Cool. Thanks very much @ravenjohn!
