### ISSUE TITLE
[034] - Some suggestions for the UX

### ISSUE THREAD

**Issue by nhvu1988** [anyTV/HeartbeatTM#45]
1. In videos tabs
    1. The "Retrieve all" button should shows as the same position with the search textbox in commenters tab
    2. After press "Retrieve all", don't reload all videos and update the sync icon for each video, it's not good when user has a significant amount of videos. Just change the number of processed / total videos.
    3. After retrieved all comments, don't refresh the page, just reload data using ajax again (or call the search function with keyword is empty)
    4. Can't click to the title to view its detail
    5. When user want to retrieve the videos manually, don't update the process status beside the "Retrieve all" button, update the sync icon is enough.
    6. Hide the pagination if has one page only
    7. Can we cache/store the data, so user can "back to videos" faster? It take a long time for refreshing the unchanged data when user go to view detail for each video.

2. Viewing video's detail
    1. Hide button "Retrieve all" 
    2. Remove button "Update commenters", replace it with sync icon and the same function

**Comment by cedricabuso** [comment]
1.
    i :heavy_check_mark: 
    ii. :heavy_check_mark:
    iii. :heavy_check_mark:
    iv. :heavy_check_mark:
    v. :heavy_check_mark:
    vi. :heavy_check_mark:
    vii. :hammer: 
2.
    i. :heavy_check_mark:
    ii. :heavy_check_mark:
